"""
core/shortener.py

The core engine. Two in-memory hash maps give O(1) average-case operations:

    code_to_url: short_code -> long_url   (lookup / redirect path)
    url_to_code: long_url   -> short_code (duplicate detection on create)

Short codes are generated by hashing the long URL (core/hashing.py) and
Base62-encoding the result (core/base62.py) -- not a random/sequential
counter -- so the system is "hash-based indexing" as described in the
project summary, while still guaranteeing uniqueness via collision handling:

    1. Compute fingerprint(url, attempt=0) -> Base62-encode -> candidate code
    2. If candidate is unused: assign it.
    3. If candidate is already used by the SAME url: duplicate detected,
       return the existing code (no new entry created).
    4. If candidate is already used by a DIFFERENT url: collision. Retry
       with fingerprint(url, attempt=1), then attempt=2, etc.
    5. If MAX_ATTEMPTS hash-based retries all collide (astronomically
       unlikely at any realistic scale -- see REPORT.md for the back-of-
       envelope probability), fall back to a monotonically increasing
       internal counter, Base62-encoded, which is unique by construction.

All operations also write through to a pluggable storage backend
(storage/persistence.py) so links survive process restarts.
"""

import threading
import time
from typing import Optional, Dict

from core import base62
from core.hashing import fingerprint

MAX_HASH_ATTEMPTS = 5
MIN_CODE_LENGTH = 6


class DuplicateURLError(Exception):
    """Not used as a hard error in the default flow (duplicates are handled
    gracefully by returning the existing code) -- kept available for callers
    that want strict-mode behavior instead."""


class URLShortener:
    def __init__(self, store=None):
        from storage.persistence import InMemoryStore

        self.store = store or InMemoryStore()
        self.code_to_url: Dict[str, str] = {}
        self.url_to_code: Dict[str, str] = {}
        self._fallback_counter = 0
        self._lock = threading.Lock()  # guards the create path against races

        self._load_from_store()

    # ------------------------------------------------------------- lifecycle

    def _load_from_store(self):
        """Rehydrate in-memory maps from persistent storage -- this is what
        makes link recovery work across sessions/restarts."""
        rows = self.store.load_all()
        for row in rows:
            self.code_to_url[row["short_code"]] = row["long_url"]
            self.url_to_code[row["long_url"]] = row["short_code"]
        if rows:
            # keep the fallback counter ahead of any previously-used
            # fallback-generated codes so we never reissue one
            self._fallback_counter = len(rows)

    # ------------------------------------------------------------- creation

    def shorten(self, long_url: str) -> str:
        """Returns a short code for `long_url`. If this URL was already
        shortened before, returns the SAME code (duplicate detection) rather
        than creating a redundant entry -- this is the O(1) duplicate check
        via the url_to_code reverse index.
        """
        if not long_url or not long_url.strip():
            raise ValueError("long_url must be a non-empty string")
        long_url = long_url.strip()

        with self._lock:
            existing = self.url_to_code.get(long_url)
            if existing is not None:
                return existing  # duplicate detected, O(1)

            code = self._generate_unique_code(long_url)
            self.code_to_url[code] = long_url
            self.url_to_code[long_url] = code
            self.store.insert(code, long_url, created_at=time.time())
            return code

    def _generate_unique_code(self, long_url: str) -> str:
        for attempt in range(MAX_HASH_ATTEMPTS):
            candidate_int = fingerprint(long_url, attempt=attempt)
            candidate_code = base62.pad(base62.encode(candidate_int), MIN_CODE_LENGTH)

            occupant = self.code_to_url.get(candidate_code)
            if occupant is None:
                return candidate_code
            if occupant == long_url:
                # Shouldn't happen (caller already checked url_to_code), but
                # safe to short-circuit here too.
                return candidate_code
            # else: real collision (different URL already owns this code) -> retry

        # Exhausted hash-based attempts (collision storm or pathological
        # input) -- fall back to a counter-based code, unique by construction.
        return self._fallback_code()

    def _fallback_code(self) -> str:
        while True:
            self._fallback_counter += 1
            code = "Z" + base62.pad(base62.encode(self._fallback_counter), MIN_CODE_LENGTH - 1)
            if code not in self.code_to_url:
                return code

    # ------------------------------------------------------------- retrieval

    def resolve(self, short_code: str) -> Optional[str]:
        """O(1) average-case lookup of the original URL, and records a click
        for analytics. Returns None if the code doesn't exist."""
        long_url = self.code_to_url.get(short_code)
        if long_url is None:
            return None
        self.store.record_click(short_code)
        return long_url

    def exists(self, short_code: str) -> bool:
        return short_code in self.code_to_url

    # ------------------------------------------------------------- analytics

    def stats_for(self, short_code: str) -> Optional[Dict]:
        return self.store.get(short_code)

    def overview(self) -> Dict:
        return {
            "total_urls": self.store.count(),
            "total_clicks": self.store.total_clicks(),
        }

    def top_urls(self, n: int = 10):
        return self.store.top_urls(n)

    def close(self):
        self.store.close()
